# Generated by Django 5.0.3 on 2024-03-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ozon_api_key', models.CharField(max_length=255)),
                ('ozon_client_id', models.CharField(max_length=255)),
                ('wildberries_api_key', models.CharField(max_length=255)),
                ('yandex_market_api_key', models.CharField(max_length=255)),
            ],
        ),
    ]
