# Generated by Django 5.0.3 on 2024-03-25 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='code128',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='main_sticker',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='small_sticker',
        ),
        migrations.AddField(
            model_name='product',
            name='code128',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='ShipmentChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packaging.saleschannel')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packaging.shipment')),
            ],
        ),
        migrations.AddField(
            model_name='shipment',
            name='channels',
            field=models.ManyToManyField(through='packaging.ShipmentChannel', to='packaging.saleschannel'),
        ),
    ]
