# Generated by Django 5.0.3 on 2024-03-26 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0004_product_category_product_description_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
