# Generated by Django 5.0.3 on 2024-03-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0006_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='articul',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
