# Generated by Django 5.0.3 on 2024-03-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0008_alter_product_price_alter_product_quantity_at_fbo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity_at_fbo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity_in_stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
