# Generated by Django 5.0.3 on 2024-03-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0011_product_moysklad_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='articul',
            new_name='article',
        ),
    ]
