# Generated by Django 5.0.3 on 2024-03-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0012_rename_articul_product_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='moysklad_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.ManyToManyField(to='packaging.customuser'),
        ),
    ]
