# Generated by Django 5.0.3 on 2024-03-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0015_customuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='moysklad_pass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='moysklad_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
