# Generated by Django 5.0.3 on 2024-03-27 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0016_customuser_moysklad_pass_customuser_moysklad_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPlaceArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_type', models.CharField(blank=True, choices=[('OZON', 'OZON'), ('Wildeberries', 'Wildberries'), ('YandexMarket', 'Yandex Market')], max_length=100, null=True)),
                ('code', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='marketplaces_articles',
            field=models.ManyToManyField(to='packaging.marketplacearticle'),
        ),
    ]
