# Generated by Django 5.0.3 on 2024-03-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0017_marketplacearticle_product_marketplaces_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
