# Generated by Django 5.0.3 on 2024-03-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0018_shipment_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='files',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
