# Generated by Django 5.0.3 on 2024-03-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0019_alter_shipment_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='files',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
