# Generated by Django 5.0.3 on 2024-03-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0020_alter_shipment_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='marketplace_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='moysklad_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
