# Generated by Django 5.0.3 on 2024-03-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0021_shipment_marketplace_id_shipment_moysklad_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='files',
            new_name='minipdf',
        ),
        migrations.AddField(
            model_name='shipment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pdf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
