# Generated by Django 5.0.3 on 2024-03-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0022_rename_files_shipment_minipdf_shipment_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='product',
        ),
        migrations.AddField(
            model_name='shipment',
            name='product',
            field=models.ManyToManyField(to='packaging.product'),
        ),
    ]
