# Generated by Django 5.0.3 on 2024-03-27 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0024_rename_product_shipment_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='packaging.customuser'),
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
