# Generated by Django 5.0.3 on 2024-03-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0025_alter_shipment_seller_delete_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='products_codes128',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
