# Generated by Django 5.0.3 on 2024-03-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0026_shipment_products_codes128'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marketplace_href',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='place',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
