# Generated by Django 5.0.3 on 2024-03-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packaging', '0027_product_marketplace_href_product_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='products_skus',
            field=models.TextField(blank=True, null=True),
        ),
    ]
